
---

- name: Install and set up dhclient
  block: 
  - name: Install dhclient
    apt:
      name: isc-dhcp-client
      state: present

  - name: Create dhclient hook dir
    file:
      path: /etc/dhcp/dhclient-exit-hooks.d
      state: directory
      owner: root
      group: root
      mode: '0755'

  - name: Add hook to resolve conf
    copy:
      src: stop_overwrite_resolvconf
      dest: /etc/dhcp/dhclient-exit-hooks.d/stop_overwrite_resolvconf
      owner: root
      group: root
      mode: '0755'
  tags: dhclient
