--- 

- name: Generate tls key
  command:
    cmd: openvpn --genkey --secret {{ openvpn_config_server_dir }}/ta.key

- name: Set permission for tls key
  file:
    path: "{{ openvpn_config_server_dir }}/ta.key"
    owner: "{{ openvpn_user }}"
    group: "{{ openvpn_group }}"
    mode: "640"

- name: Fetch hosts config
  fetch:
    src: "{{ openvpn_config_server_dir }}/ta.key"
    dest: openvpn_client_ca/ta.key
    flat: true

- name: Add openvpn config
  template:
    src: openvpn.conf.j2
    dest: "{{ openvpn_config_server_dir }}/openvpn.conf"
    owner: "{{ openvpn_user }}"
    group: "{{ openvpn_group }}"
    mode: '0644'
  notify: Restart openvpn
