--- 

- name: Create OpenVPN systemd service file
  template:
    src: openvpn.service.j2
    dest: /etc/systemd/system/openvpn@server.service
    mode: '0644'
  register: openvpn_service
  notify: Restart openvpn
  ignore_errors: true
 
- name: Reload systemd
  systemd:
    daemon_reload: true
  when: openvpn_service is changed

- name: Enable openvpn service
  systemd:
    name: openvpn@server
    enabled: yes
    masked: no