---

- name: Flush all iptables rules
  command: iptables -F

- name: Flush all iptables NAT rules
  command: iptables -t nat -F

- name: Flush all iptables mangle rules
  command: iptables -t mangle -F

- name: Delete all custom chains
  command: iptables -X

- name: Remove saved iptables rules file (Debian/Ubuntu)
  file:
    path: /etc/iptables/rules.v4
    state: absent
