---

- name: Download Envoy GPG key
  get_url:
    url: https://apt.envoyproxy.io/signing.key
    dest: /tmp/signing.key
    mode: '0644'
    owner: root
    group: root

- name: Convert GPG key to binary format
  ansible.builtin.command:
    cmd: gpg --dearmor -o /usr/share/keyrings/envoy-keyring.gpg /tmp/signing.key
  args:
    creates: /usr/share/keyrings/envoy-keyring.gpg
    
- name: Add HashiCorp repository to sources.list
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/envoy.list
    line: "deb [arch=amd64 signed-by=/usr/share/keyrings/envoy-keyring.gpg] https://apt.envoyproxy.io {{ ansible_lsb.codename }} main"
    create: yes

- name: Update apt cache
  apt:
    update_cache: yes

- name: Clean up temporary GPG file
  file:
    path: /tmp/envoy.gpg
    state: absent