---

- name: Download HashiCorp GPG key
  get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /tmp/hashicorp.gpg
    mode: '0644'
    owner: root
    group: root

- name: Convert GPG key to binary format
  ansible.builtin.command:
    cmd: gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg /tmp/hashicorp.gpg
  args:
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

- name: Add HashiCorp repository to sources.list
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/hashicorp.list
    line: "deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main"
    create: yes

- name: Update apt cache
  apt:
    update_cache: yes

- name: Clean up temporary GPG file
  file:
    path: /tmp/hashicorp.gpg
    state: absent