---

consul_cluster: "my-cluster"
consul_port: 8500
vault_port: 8200


vault_addr: "http://vault.{{ domain_name }}:{{ vault_port }}"
consul_http_addr: "http://consul.{{ domain_name }}:{{ consul_port }}"
