---

subnet_mask: 24

# DHCP varaibles 
dhcp_server_ip: 172.16.1.1

# tinc dhcp range
vpn_dhcp_range_start_ip: 172.16.1.1
vpn_dhcp_range_end_ip: 172.16.1.10
vpn_dhcp_lease_time: 365d

# range for vms
vms_subnet: 192.168.100.0/24
vms_dhcp_lease_time: 30d
bridge_iface: "br0"
bridge_ip_range_start: 192.168.100.1
bridge_ip_range_end: 192.168.100.9
bridge_dhcp_lease_time: 365d

# variables for tinc
vpn_name: "privatecloud"
vpn_subnet: 172.16.1.0/24
vpn_subnet_id: "172.16.1.0"
vpn_port: 655

# variable for iface, which is attach tinc interface and firecracker interfaces
firecracker_iface: tap1
vpn_iface: tap0

domain_name: my-cluster.internal
dns_server: 172.16.1.1
dns_log_path: "/var/log/dnsmasq.log"

# openvpn 
openvpn_iface: tap1
openvpn_subnet: "172.16.100.0/24"
openvpn_subnet_id: "172.16.100.0"
openvpn_ip_range_start: "172.16.100.10"
openvpn_ip_range_end: "172.16.100.100"
openvpn_gw_ip: "172.16.100.1"
openvpn_dhcp_lease_time: 48h