---

- name: Add nomad user
  import_tasks: users.yaml
  tags: nomad_user

- name: Install nomad
  import_tasks: install.yaml
  tags: nomad_install

- name: Add nomad files dirs
  import_tasks: files.yaml
  tags: nomad_files

- name: Add nomad service
  import_tasks: service.yaml
  tags: nomad_service

- name: Set facts
  import_tasks: set_facts.yaml
  tags: 
    - nomad_fact
    - nomad_config
    - nomad_tokens
    - nomad_management_token

- name: Set nomad config
  import_tasks: config.yaml
  tags: nomad_config 

- name: Bootstarp nomad acl
  import_tasks: acl_init.yaml
  tags: nomad_acl_init
  when: "inventory_hostname in groups['master']"
  environment:
    NOMAD_ADDR: "{{ nomad_addr }}"

- name: Management token
  import_tasks: management_token.yaml
  tags: nomad_management_token
  when: "inventory_hostname in groups['master']"
  environment:
    NOMAD_ADDR: "{{ nomad_addr }}"
    NOMAD_TOKEN: "{{ nomad_token }}"

- name: Add Policies and tokens
  include_tasks: 
    file: policies_tokens.yaml
    apply:
      tags: nomad_tokens
  with_items: "{{ nomad_policies }}"
  when:
    - inventory_hostname in groups['master'] and nomad_token is defined
  tags: nomad_tokens