---

- name: Create nomad service
  template: 
    src: nomad.service.j2
    dest: /etc/systemd/system/nomad.service
    owner: root
    group: root
    mode: 0644
  register: nomad_service
  ignore_errors: true
 
- name: Reload systemd
  systemd:
    daemon_reload: true
  when: nomad_service is changed

- name: Enable nomad service
  systemd:
    name: nomad
    enabled: yes
    masked: no