---

vault_policies:
  - name: ui

  - name: admin

  - name: consul
    role: consul
    token_ttl: 1h
    token_max_ttl: 4h
    auth_path: consul

  - name: nomad
    role: nomad
    token_ttl: 1h
    token_max_ttl: 4h
    auth_path: nomad
  
