--- 

- name: Install network packages
  apt:
    name: 
      - ifupdown
      - bridge-utils
    state: present
    update_cache: true

- name: Configure bridge interface with IP from dhcp server
  ansible.builtin.template:
    src: bridge.cfg.j2
    dest: /etc/network/interfaces.d/{{ bridge_iface }}.cfg
    owner: root
    group: root
    mode: '0644'
  notify: 
    - Restart bridge interface

- name: Add dnsmasq conf
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.d/{{ bridge_iface }}.conf
    mode: '0644'
  notify: Restart dnsmasq
  when: priv_ip == dhcp_server_ip
  tags: dnsmasq_bridge