--- 

- name: Install network packages
  apt:
    name: 
      - ifupdown
      - bridge-utils
    state: present
    update_cache: true

- name: Configure bridge interface with IP from dhcp server
  ansible.builtin.template:
    src: bridge.cfg.j2
    dest: /etc/network/interfaces.d/{{ bridge_iface }}.cfg
    owner: root
    group: root
    mode: '0644'
  notify: Restart bridge interface
