--- 

- name: Install chrony for ntp synchro
  apt: 
    name: chrony
    state: present

- name: Add chrony dir
  file:
    path: /etc/chrony
    state: directory
    mode: '0644'

- name: Add chrony config
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    mode: '0644'
  notify: Restart chrony

- name: Start chrony conf
  systemd: 
    name: chrony
    state: started 
    enabled: true