---

- name: Stop named dns server
  systemd:
    name: named
    state: stopped
    enabled: no

- name: Install dnsmasq
  package:
    name: dnsmasq
    state: present

- name: Create dnsmasq.d 
  file:
    path: /etc/dnsmasq.d
    state: directory 
    mode: '0644'

- name: Set dnsmasq config
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    mode: '0644'
  notify: Restart dnsmasq

- name: Set cluster config
  template:
    src: cluster.conf.j2
    dest: /etc/dnsmasq.d/cluster.conf
  notify: Restart dnsmasq

- name: Set cluster config
  template:
    src: openvpn.conf.j2
    dest: /etc/dnsmasq.d/openvpn.conf
  notify: Restart dnsmasq

- name: Start dnsmasq service
  systemd:
    name: dnsmasq
    state: started
    enabled: true