---

- name: Prepare localhost
  hosts: localhost
  tasks:
    - name: Generate ssh key for vms
      openssh_keypair:
        path: "../ssh_key/vms_id_rsa"
        force: true
  tags: prepare_local

- name: Prepare servers
  hosts: all
  become: true
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"
      tags: hostname

    - name: Enable IP forwarding at runtime
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
      tags: ip_forward 
  roles:
    - role: chrony
      tags: ntp
    - role: dhclient
      tags: dhclient 
    - role: firewall
      tags: firawall
  tags: prepare

# - name: DHCP server
#   hosts: master
#   become: true
#   roles:
#     - role: dnsmasq
#       tags: dhcp

- name: Mesh VPN
  hosts: all
  become: true
  serial: 1
  roles:
    - role: tinc
      tags: tinc 

- name: Hashicorp Cluster
  hosts: all
  become: true 
  roles: 
    - role: apt_source
      tags: apt_source
    - role: consul
      tags: consul
    - role: vault
      tags: vault

# Not enough resources, so the cluster won't have the microvms
# - name: Seting up Firecracker 
#   hosts: all
#   become: true
#   vars: 
#     ssh_key_dir: "{{ project_absolute_path }}/ssh_key"
#   roles:
#     - role: firecracker
#       tags: firecracker
#     - role: bridge
#       tags: bridge
