---

- name: Init pki
  command:
    cmd: easyrsa init-pki
    chdir: "{{ easyrsa_ca_dir }}"
  args:
    creates: "{{ easyrsa_ca_dir }}/pki"

- name: Set OpenVPN client name from environment variable
  set_fact:
    openvpn_client_name: "{{ lookup('env', 'OPENVPN_CLIENT') }}"

- name: Generate tls key
  command:
    cmd: openvpn --genkey --secret {{ openvpn_config_server_dir }}/ta.key

- name: Set permission for tls key
  file:
    path: "{{ openvpn_config_server_dir }}/ta.key"
    owner: "{{ openvpn_user }}"
    group: "{{ openvpn_group }}"
    mode: "640"

- name: Add vars file for easyrsa
  template:
    src: easyrsa_vars.j2
    dest: "{{ easyrsa_ca_dir }}/pki/vars"
    owner: "{{ openvpn_user }}"
    group: "{{ openvpn_group }}"
    mode: '0644'

- name: Generate dh.pem
  command:
    cmd: easyrsa gen-dh
    chdir: "{{ easyrsa_ca_dir }}"
  args:
    creates: "{{ easyrsa_ca_dir }}/pki/dh.pem"

- name: Build the CA
  command:
    cmd: easyrsa build-ca nopass
    chdir: "{{ easyrsa_ca_dir }}"
  args:
    creates: "{{ easyrsa_ca_dir }}/pki/ca.crt"

- name: Generate server key and CSR
  command:
    cmd: easyrsa --req-cn="{{ domain_name }}-OpenVPN Server CA" gen-req server nopass
    chdir: "{{ easyrsa_ca_dir }}"
  args:
    creates: "{{ easyrsa_ca_dir }}/pki/private/server.key"

- name: Sign server certificate
  command:
    cmd: easyrsa sign-req server server
    chdir: "{{ easyrsa_ca_dir }}"
  environment:
    EASYRSA_BATCH: "1"  # Skip interactive prompts
  args:
    creates: "{{ easyrsa_ca_dir }}/pki/issued/server.crt"

- name: Distribute server certificates
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: true
  with_items:
    - { src: "{{ easyrsa_ca_dir }}/pki/ca.crt", dest: "{{ openvpn_config_server_dir }}/ca.crt" }
    - { src: "{{ easyrsa_ca_dir }}/pki/issued/server.crt", dest: "{{ openvpn_config_server_dir }}/server.crt" }
    - { src: "{{ easyrsa_ca_dir }}/pki/private/server.key", dest: "{{ openvpn_config_server_dir }}/server.key" }
    - { src: "{{ easyrsa_ca_dir }}/pki/dh.pem", dest: "{{ openvpn_config_server_dir }}/dh.pem" }

- name: Set correct permission for key
  file:
    path: "{{ openvpn_config_server_dir }}/{{ item }}"
    owner: "{{ openvpn_user }}"
    group: "{{ openvpn_group }}"
    mode: "600"
  with_items:
    - server.key
    - dh.pem

- name: Set correct permission for cert
  file:
    path: "{{ openvpn_config_server_dir }}/{{ item }}"
    owner: "{{ openvpn_user }}"
    group: "{{ openvpn_group }}"
    mode: "640"
  with_items:
    - ca.crt
    - server.crt

